os:
  - linux
sudo: false
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - libstdc++6
      - fonts-droid
before_script:
  - git clone https://github.com/flutter/flutter.git -b alpha --depth 1
  - ./flutter/bin/flutter doctor -v
  - sudo sh -c 'curl https://storage.googleapis.com/download.dartlang.org/linux/debian/dart_unstable.list > /etc/apt/sources.list.d/dart_unstable.list'
  - sudo apt-get install dart
script:
  - ./flutter/bin/flutter test --coverage --coverage-path=lcov.info
after_success:
  - bash <(curl -s https://codecov.io/bash)
cache:
  directories:
    - $HOME/.pub-cache