# Important: Use "flutter packages get", not "pub get".
name: functional_flutter
author: David Marne <davemarne@gmail.com>
version: 0.0.1
description: Functional utility library for flutter
homepage: https://github.com/davidmarne/functional_flutter
dependencies:
  built_redux: ^7.0.0
  flutter:
    sdk: flutter
  flutter_built_redux: ^0.4.0
  meta: ^1.0.3

dev_dependencies:
  build_runner: ^0.6.0  
  built_value: ^5.0.0
  built_value_generator: ^5.0.0
  flutter_test:
    sdk: flutter
  source_gen: ^0.7.0

environment:
  sdk: ">=1.19.0 <2.0.0"
